spring:
  datasource:
    url: jdbc:h2:mem:justeat
    driverClassName: org.h2.Driver
    username: justeat
    password: justeat
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  
#KAFKA
kafka:
  bootstrapServer: localhost:9092
  consumers:
    consumerGroup: justeat-consumer
    maxPollRecords: 3
    concurrency: 1
    properties:
      spring.json.trusted.packages: "com.jet.restaurant.frontend.api.topic.Restaurant"
  topic:
    status-update: UPDATE_STATUS

search:
  retry:
    backoff:
      maxAttempts: 3
      intervalMillis: 10

server:
  port: 8090

application:
  name: JET
